main:
  - name: nav.about
    pageRef: /about
    weight: 20
    params:
      icon: about
  - name: nav.posts
    pageRef: /posts
    weight: 20
    params:
      icon: posts
  - name: nav.publications
    pageRef: /publications
    weight: 25
    params:
      icon: book-open
  - name: nav.tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags
  - name: nav.archives
    pageRef: /archives
    weight: 50
    params:
      icon: archive

# footer social link
social:
  - name: LinkedIn
    url: https://linkedin.com/in/yahel1216
    weight: 30
    params:
      icon: linkedin
  - name: Email
    url: mailto:yahel.uffenheimer@mail.huji.ac.il
    weight: 40
    params:
      icon: email

